on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  RUST_TEST_THREADS: 1
  TEST_PW: Testpw123!+

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, windows-2019]
        target:
          [x86_64-pc-windows-msvc, i686-pc-windows-msvc, x86_64-pc-windows-gnu]
        channel: [nightly]
        include:
          - target: i686-pc-windows-gnu
            channel: 1.65.0
            os: windows-2022
          - target: x86_64-unknown-linux-gnu
            channel: nightly
            os: ubuntu-latest
          - target: x86_64-unknown-linux-gnu
            channel: 1.65.0
            os: ubuntu-20.04
        exclude:
          - target: x86_64-pc-windows-gnu  # For some reason broken while compiling examples: winauth-f585191527f6477b.exe --nocapture` (exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND)
            os: windows-2019
            channel: nightly
    steps:
      - if: runner.os == 'windows'
        run: |
          cmd.exe /c "net user %USERNAME% %TEST_PW%"
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.channel }}
          target: ${{ matrix.target }}
      - if: matrix.target == 'i686-pc-windows-gnu'
        uses: MinoruSekine/setup-scoop@main
      - if: matrix.target == 'i686-pc-windows-gnu'
        run: |
          scoop install -a 32bit mingw
          Join-Path (Resolve-Path ~).Path "scoop\apps\mingw\current\bin" >> $env:GITHUB_PATH
      - run: cargo +${{ matrix.channel }} build --tests --target ${{ matrix.target }}
      - run: cargo +${{ matrix.channel }} test --target ${{ matrix.target }} -- --nocapture
